<?php
/**
 * MessagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MessagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelScheduledJob
     *
     * .
     *
     */
    public function testCancelScheduledJob()
    {
    }

    /**
     * Test case for getInboxMessages
     *
     * .
     *
     */
    public function testGetInboxMessages()
    {
    }

    /**
     * Test case for getMessageById
     *
     * .
     *
     */
    public function testGetMessageById()
    {
    }

    /**
     * Test case for getMessages
     *
     * .
     *
     */
    public function testGetMessages()
    {
    }

    /**
     * Test case for scheduleMessage
     *
     * .
     *
     */
    public function testScheduleMessage()
    {
    }

    /**
     * Test case for sendMessage
     *
     * .
     *
     */
    public function testSendMessage()
    {
    }
}
